In [1]:
import dismech
import numpy as np

In [2]:
inds = np.stack([np.arange(12)])
imc = dismech.IMCEnergy(inds, 0.2, 0.02)

In [3]:
test_input = np.array([[
    0.0, 0.0, 0.0,  # x
    0.0, 1.0, 0.0,  # y
    0.0, 1.01, 0.0,  # a
    0.0, 2.01, 0.0   # b
], [
    0.0, 0.0, 0.0,  # x
    1.0, 1.0, 0.0,  # y
    1.0, 0.0, 0.01,  # a
    0.0, 1.0, 0.01   # b
], [
    0.0, 0.0, 0.0,  # x
    0.0, 1.0, 0.0,  # y
    -1.0, 1.01, 0.0,  # a
    1.0, 1.01, 0.0   # b
]])
for t in test_input:
    print("Delta (min): {}".format(imc.get_Delta(t)))
    print("t: {}, u: {}".format(*imc.get_lumelsky_coeff(t)))
    print("correct ind: {}".format(imc._get_lumelsky_mask(*imc.get_lumelsky_coeff(t))))

Delta (min): [0.01]
t: [1.], u: [0.]
correct ind: [[ 3  4  5  0  1  2  6  7  8  9 10 11]]
Delta (min): [0.01]
t: [0.5], u: [0.5]
correct ind: [[ 0  1  2  3  4  5  6  7  8  9 10 11]]
Delta (min): [0.01]
t: [1.], u: [0.5]
correct ind: [[ 3  4  5  0  1  2  6  7  8  9 10 11]]


In [4]:
np.set_printoptions(linewidth=200, threshold=np.inf)

for t in test_input:
    g, h = imc.grad_hess_energy(t)
    print("Gradient: {}".format(g))

Gradient: [[-0.          0.05669642 -0.         -0.         -0.         -0.         -0.         -0.05669642 -0.         -0.         -0.         -0.        ]]
Gradient: [[-0.         -0.          0.02834821 -0.         -0.          0.02834821 -0.         -0.         -0.02834821 -0.         -0.         -0.02834821]]
Gradient: [[-0.          0.05669642 -0.         -0.         -0.         -0.         -0.         -0.02834821 -0.         -0.         -0.02834821 -0.        ]]


```matlab
>> grad_E_con_p2p([ 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.01, 0.0, 0.0, 2.01, 0.0, .010, 0.02, 75])

ans =

         0    0.0567         0         0         0         0         0   -0.0567         0         0         0         0

>> grad_E_con_e2e([ 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.01, 0.0, 1.0, 0.01, .010, 0.02, 75])

ans =

         0         0    0.0283         0         0    0.0283         0         0   -0.0283         0         0   -0.0283

>> grad_E_con_p2e([ 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, -1.0, 1.01, 0.0, 1.0, 1.01, 0.0, .010, 0.02, 75])

ans =

         0    0.0567         0         0         0         0         0   -0.0283         0         0   -0.0283         0
```

In [7]:
np.set_printoptions(linewidth=200, threshold=np.inf)

for t in test_input:
    g, h = imc.grad_hess_energy(t)
    print(h)
    print("\n")

[[[-5.66964166  0.          0.          0.          0.          0.          5.66964166  0.          0.          0.          0.          0.        ]
  [ 0.          2.04223315  0.          0.          0.          0.          0.         -2.04223315  0.          0.          0.          0.        ]
  [ 0.          0.         -5.66964166  0.          0.          0.          0.          0.          5.66964166  0.          0.          0.        ]
  [ 0.          0.          0.          0.          0.          0.          0.          0.          0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.          0.          0.          0.          0.          0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.          0.          0.          0.          0.          0.          0.          0.          0.        ]
  [ 5.66964166  0.          0.          0.          0.          0.         -5.66964166  0.          0.          

```matlab
>> hess_E_con_p2p([ 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.01, 0.0, 0.0, 2.01, 0.0 ,.010,0.02,75])

ans =

       NaN         0         0         0         0         0       NaN         0         0         0         0         0
         0    2.0422         0         0         0         0         0   -2.0422         0         0         0         0
         0         0       NaN         0         0         0         0         0       NaN         0         0         0
         0         0         0         0         0         0         0         0         0         0         0         0
         0         0         0         0         0         0         0         0         0         0         0         0
         0         0         0         0         0         0         0         0         0         0         0         0
       NaN         0         0         0         0         0       NaN         0         0         0         0         0
         0   -2.0422         0         0         0         0         0    2.0422         0         0         0         0
         0         0       NaN         0         0         0         0         0       NaN         0         0         0
         0         0         0         0         0         0         0         0         0         0         0         0
         0         0         0         0         0         0         0         0         0         0         0         0
         0         0         0         0         0         0         0         0         0         0         0         0

>> hess_E_con_e2e([ 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.01, 0.0, 1.0, 0.01, .010, 0.02, 75])

ans =

   NaN     0   NaN   NaN     0   NaN   NaN     0   NaN   NaN     0   NaN
     0   NaN   NaN     0   NaN   NaN     0   NaN   NaN     0   NaN   NaN
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
   NaN     0   NaN   NaN     0   NaN   NaN     0   NaN   NaN     0   NaN
     0   NaN   NaN     0   NaN   NaN     0   NaN   NaN     0   NaN   NaN
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
   NaN     0   NaN   NaN     0   NaN   NaN     0   NaN   NaN     0   NaN
     0   NaN   NaN     0   NaN   NaN     0   NaN   NaN     0   NaN   NaN
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
   NaN     0   NaN   NaN     0   NaN   NaN     0   NaN   NaN     0   NaN
     0   NaN   NaN     0   NaN   NaN     0   NaN   NaN     0   NaN   NaN
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

>> hess_E_con_p2e([ 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, -1.0, 1.01, 0.0, 1.0, 1.01, 0.0, .010, 0.02, 75])

ans =

       NaN         0       NaN         0         0         0       NaN    0.0283       NaN       NaN   -0.0283       NaN
         0       NaN       NaN         0         0         0         0       NaN       NaN         0       NaN       NaN
       NaN       NaN       NaN         0         0         0       NaN       NaN       NaN       NaN       NaN       NaN
         0         0         0         0         0         0         0         0         0         0         0         0
         0         0         0         0         0         0         0         0         0         0         0         0
         0         0         0         0         0         0         0         0         0         0         0         0
       NaN         0       NaN         0         0         0       NaN   -0.0142       NaN       NaN    0.0142       NaN
    0.0283       NaN       NaN         0         0         0   -0.0142       NaN       NaN   -0.0142       NaN       NaN
       NaN       NaN       NaN         0         0         0       NaN       NaN       NaN       NaN       NaN       NaN
       NaN         0       NaN         0         0         0       NaN   -0.0142       NaN       NaN    0.0142       NaN
   -0.0283       NaN       NaN         0         0         0    0.0142       NaN       NaN    0.0142       NaN       NaN
       NaN       NaN       NaN         0         0         0       NaN       NaN       NaN       NaN       NaN       NaN   
```